// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryovhqrrljfaprftjfbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5b3ZocXJybGpmYXByZnRqZmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTY1NDcsImV4cCI6MjA3MTYzMjU0N30.6ug4EwH0pmhzmdOMIiw9kXxSBCI51RTKfWooPXF9cfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});